### ISSUE TITLE
`resolve_polytomies` method fails on some Glottolog trees

### ISSUE THREAD

**Issue by xrotwang** [glottobank/python-newick#11]
``` python
import urllib
import newick

fp = urllib.urlopen('http://glottolog.org/static/trees/tree-glottolog-newick.txt')
for tree in newick.loads(fp.read().decode('utf8')):
    print(tree.name)
    tree.resolve_polytomies()
```

fails with

```
(newick)dlt5502178l:~/venvs/newick$ python glottolog_resolve.py 
'Bookkeeping [book1242]'
Traceback (most recent call last):
  File "glottolog_resolve.py", line 7, in <module>
    tree.resolve_polytomies()
  File "/home/shh.mpg.de/forkel/venvs/newick/python-newick/newick.py", line 208, in resolve_polytomies
    assert self.is_binary
AssertionError
```

**Comment by lmaurits** [comment]
@Anaphory, is this related to the problems you ran into near the end of your time at Auckland?  I know we discussed making changes to this method to better handle some edge cases.

**Comment by xrotwang** [comment]
@lmaurits I just came across this when someone told me R (whatever package) wouldn't be able to deal with the Glottolog trees, and part of the reason seemed to be that they were not binary.

**Comment by xrotwang** [comment]
It turns out `resolve_polytomies` did work, but I had trees with singletons! So running `tree.remove_redundant_nodes()` before `resolve_polytomies()` did the trick. So I guess we should remove the `assert self.is_binary` statement in `resolve_polytomies`, but may add a method `binarize` which chains these two calls?
