### ISSUE TITLE
Extend `prune` method to also handle non-leaf nodes

### ISSUE THREAD

**Issue by xrotwang** [glottobank/python-newick#12]
The `prune` method e.g. on `ete2.TreeNode` objects handles also pruning of internal nodes. To make this package a drop-in replacement in more cases, and to make the functionality more congruent with what may be expected, we might want to extend our implementation of `prune` to cover this case as well.

**Comment by SimonGreenhill** [comment]
+1 it's annoying to have to loop over child nodes and delete them from there. It's being blocked by this check:

```
        if not all([n.is_leaf for n in leaves]):
            raise ValueError("prune only accepts leaf nodes")

```

...which does not seem necessary to me?

**Comment by xrotwang** [comment]
I'm not really familiar with the expected default behaviour of pruning, but maybe we could start by adding a couple of test cases outlining the desired results?
