### ISSUE TITLE
remove_redundant_nodes does not do that.

### ISSUE THREAD

**Issue by Anaphory** [glottobank/python-newick#14]
```
    import newick
    R = newick.loads("((A:1,B:1):1,C:1)")[0]
    R.prune_by_names(["A"])
    R.newick
    # '((B:1):1,C:1)'
    R.remove_redundant_nodes(True)
    R.newick
    # '(:1,C:1)'
```

Expected output after the last line would be `'(B:2,C:1)'` instead.

**Comment by LinguList** [comment]
thanks, I can't offer a solution right now, but this helps, will look into it later on.

**Comment by Anaphory** [comment]
I can offer this one, but I'm sure it's not optimal. I think I have discussed issues like this with @lmaurits before, and he wrote this function, so we might come up with something reasonable.

```
def remove_redundant_nodes(self, preserve_lengths=True):
    """
    Remove all nodes which have only a single child, and attach their
    grandchildren to their parent.  The resulting tree has the minimum
    number of internal nodes required for the number of leaves.
    :param preserve_lengths: If true, branch lengths of removed nodes are \
    added to those of their children.
    """
    for n in self.walk(mode="preorder"):
        while len(n.descendants) == 1:
            print("Only child:",n.descendants[0].name)
            only_child = n.descendants.pop()
            if only_child.descendants:
                for grandchild in only_child.descendants:
                    n.add_descendant(grandchild)
                    if preserve_lengths:
                        grandchild.length += only_child.length
            else:
                #Only child is a leaf: Take its place – This would
                #be much cleaner if we knew our parents.
                if preserve_lengths:
                    only_child.length += n.length
                for (attr, val) in vars(only_child).items():
                    setattr(n, attr, val)
```

**Comment by LinguList** [comment]
would you like to propose this as a PR? You could also provide tests, and we could review it together. And your contribution would also be tracked.

**Comment by Anaphory** [comment]
I am not suggesting that as such yet, because (a) it's not tested, and (b) it looks awfully hackish to start with. I'm giving it as a working pseudocode-outline for possible semantics. [And as something I can point to if it leads to problems down the line for myself, so I can say “And this is why that approach does not work”]

**Comment by Anaphory** [comment]
In general, I think it's better semantics if _always the child node is kept and the parent of a single child thrown away_, but an implementation of that requires the child to know its parent, some way of keeping track of parents in the method, or dealing with grandchildren of parents of single children with some special casing for the root.

So it's not something I can just put together in a few minutes to see whether that makes my other problems go away, which is my priority right now.

**Comment by LinguList** [comment]
Sorry, if this is useless information: I lost track of python-newick two months ago, since I forgot to mark to be informed about changes, but initially, I was adding the feature to the code, so that a child always knows both parents and children ([pull #1](https://github.com/glottobank/python-newick/pull/1)). So without actually reviewing your code due to the later hour in Paris: you can always keep track of parents, since very node has a parent and descendants attribute:

``` python
>>> a = newick.loads('((a,b),(c,d));')
>>> for n in a[0].walk():
            print([x.newick for x in n.descendants], n.ancestor.newick if n.ancestor else '?')
['(a,b)', '(c,d)'] ?
['a', 'b'] ((a,b),(c,d))
[] (a,b)
[] (a,b)
['c', 'd'] ((a,b),(c,d))
[] (c,d)
```

If this doesn't help, let me just sleep, and I'll later look into it in the morning with a clearer head.

**Comment by Anaphory** [comment]
Oh, I trusted some obsolete bits of docstring somewhere.
[I have just started digging back into beastling/newick/beast code after a break of a good months, too, and my time zone is the same as yours, so I'll take you up on that offer.]

```
class Node(object):
    """
    A Node may be a tree, a subtree or a leaf.

    A Node has optional name and length (from parent) and a (possibly empty) list of
    descendants.
    """
```

**Comment by LinguList** [comment]
We should change that docstring as well.
