### ISSUE TITLE
length formatter behavior yields inconsistent output in loading a tree

### ISSUE THREAD

**Issue by LinguList** [glottobank/python-newick#17]
I don't understand this, but I think it is important to get it clear. According to the code in remove_redundant_nodes, we get the strange behaviour in line 144 of test.py

``` python
        tree2 = loads("((A:1,B:1):1,C:1)")[0]
        tree2.prune_by_names(['A'])
        assert tree2.newick == '((B:1):1,C:1)'
        tree2.remove_redundant_nodes()
        assert tree2.newick == '(C:1,B:2.0)'
```

the strange line is the last one, since we expect that the combined length of B and B.ancestor (after removal of A) is 2.0, while the rest of the nodes is formatted as integers.

The reason here is, as I think, that certain keywords are not passed in-between the methods in parse_node (line 340 in newick.py)

``` python
    s = s.strip()
    parts = s.split(')')
    if len(parts) == 1:
        descendants, label = [], s
    else:
        if not parts[0].startswith('('):
            raise ValueError('unmatched braces %s' % parts[0][:100])
        descendants, label = list(_parse_siblings(')'.join(parts[:-1])[1:])), parts[-1]
    name, length = _parse_name_and_length(label)
    return Node.create(name=name, length=length, descendants=descendants, **kw)
```

Since _parse_siblings also calls _parse_nodes, we need to call _parse_siblings(XXX, *_kw), and _parse_siblings shoudl expect a *_kw.

But this does not solve the problem, since only lengths are formatted to a float using the length_formatter, if they are freshly added to the tree (as in the remove_redundant_nodes function), not if they are instantiated the first time. This seems inconsistent:

If I load a tree and set a length formatter to formatting things to floats, I would expect to have those floats also all in the newick representation.

**Comment by xrotwang** [comment]
Yeah, that's unfortunate. We should try to think this through. So the requirements are:
- support round-tripping, i.e. `dumps(loads(s)) == s`
- numeric `length` attribute on `Node` objects

So the idea was to store the length as string (as it is encountered upon parsing newick) in `Node._length`, but make it available as number when accessing `Node.length` - mediated by a custom parser function.

I think this mechanism is sound. So when the keyword parameters are passed through to `_parse_siblings`, the problem can be solved with a custom parser:

``` python
>>> tree2 = loads("((A:1,B:1):1,C:1)", length_parser=lambda x: int(x or 0))[0]
>>> tree2.prune_by_names(['A'])
>>> tree2.remove_redundant_nodes()
>>> tree2.newick
u'(C:1,B:2)'
```

But I think your expectation of having the formatter also applied to un-altered node lengths is just in conflict with the round-trip-ability. I would argue, that not specifying a parser/formatter which fits the data in the initial newick string is an input error on behalf of the user.

**Comment by LinguList** [comment]
Okay, then I'd remove the one line that applies the length_parser to all format the strings, and we should be done, right? Having both the desired behaviour, of, say, integers as weights, using custom parsers, but also identity in loading and dumping.

**Comment by xrotwang** [comment]
I have the changes to `parse_node` and `_parse_siblings` already rolled into https://github.com/glottobank/python-newick/pull/21
So the only thing to add would be tests.
