### ISSUE TITLE
Stacked singleton root leads to infinite loop for `remove_redundant_nodes`

### ISSUE THREAD

**Issue by Anaphory** [glottobank/python-newick#23]
For `R = newick.loads("((A,B):1):2")[0]`, `R.remove_redundant_nodes()` terminates and creates `(A,B):3.0` as it should.

For two stacked singletons at the root, as in `R = newick.loads("(((A,B):1):2)")[0]`, `R.remove_redundant_nodes()` runs an infinite loop of ever-increasing root length.

**Comment by Anaphory** [comment]
To fix this, roots probably need special consideration, because for every other node, we can just remove the parent, but we cannot do that for the singleton below root, otherwise we lose the tree.

**Comment by LinguList** [comment]
you need to go for postorder! You climb the tree up and glue the child to its father.

**Comment by Anaphory** [comment]
That has other problems of elements being revisited after they have already been removed from the tree, or something like that.

**Comment by LinguList** [comment]
if you change it to "postorder", you get the stacked-ar-root immediately fixed, but the other example doesn't work anymore..

**Comment by Anaphory** [comment]
Yep, the reason is that the `father` node is visited next after `n` tried to replace it. And if `father`'s `father` is singular again, `father` tries to replace it and is added back to the tree.

The solution seems to be to use `postorder`, and to set `father.ancestor` to `None` for `father`s that die.

**Comment by LinguList** [comment]
yep, got it! It works, you want me to push the PR?

**Comment by LinguList** [comment]
sorry, I accidentally pushed to master, but I wanted to push to my branch. Yet, I hope this does the trick. I also made the test more complicated, invovling two stacked nodes, and it worked.

**Comment by Anaphory** [comment]
I'd have suggested adding a new test for it (then reporting is clearer on which case fails), and make sure that the test tree has large positive lengths and `fpectl` does not allow floating points to overflow to `inf`, such that in case of a regression the infinite loop produces a `FloatingPointError` and we know that something is wrong.

**Comment by LinguList** [comment]
you wanna go for it? Would be good to have this properly covered.

**Comment by Anaphory** [comment]
Ah, `fpectl` is not a reasonable module, and I don't know another way of catching overflows as they happen. So I guess I have nothing to contribute here.
