### ISSUE TITLE
lengths are strings internally

### ISSUE THREAD

**Issue by Anaphory** [glottobank/python-newick#29]
I just wanted to feed some floats as lengths to `newick.Node`s, which did not work because internally, our nodes must have string lengths, and only strings can be passed to the constructor. Only through the magic of the `.length` property are these strings turned into … something arbitrary and node-dependent.

- By the usual formulation of the Newick grammar, branch lengths should be “*number*”s, so the `.newick()` method must format whatever internal representation lengths may have into a (decimal) number format, using some `length_formatter`.
- When doing calculations programmatically, ie. using `.length`, as little as possible should happen. For example, `remove_redundant_nodes` does calculations with lengths, it is worrying that there is a to-string and to-float conversion going on in every step.
- It is odd that passing an apparent attribute to the constructor behaves differently from setting it on the object, so `__init__`'s `length` should behave the same as `.length`. (This also avoids the very strange `Node(length=self._length_formatter(self._length_parser('0')))` in `.resolve_polytomies()`)
- The Newick string parser needs one consistent number-parsing function.

This to me suggests

-  Drop the wrapping of `.length` in a property
-  Add formatter and parser to `parse_node()` and to `.newick()`
- Clean up `remove_redundant_nodes()`

**Comment by xrotwang** [comment]
I see Newick more as a serialization format than a grammar. Now a valuable property of a serialization format is [allowing round-tripping](https://en.wikipedia.org/wiki/Round-trip_format_conversion). To make this possible we store the length as string.

I agree that this behaviour introduces weirdness in methods like `remove_redundant_nodes` and `resolve_polytomies`. But from my point of view this is more an argument against including such methods in this library, since `python-newick` is intended as lightweight library to read and write Newick, not a full-blown tree-manipulation tool.

**Comment by Anaphory** [comment]
Oh, but the round-tripping still works under the model I suggest. You just need to specify *Do Nothing* as the number parser in `parse_node()`, the default `length_formatter` used for writing back does nothing to a string anyway.

In some sense, it might be possible to read my suggestion as a “What do the objects you try to serialize look like, anyway?” – and part of my answer is “Well, they have a length, which should be serializable, but we don't enforce how to do that.”

**Comment by xrotwang** [comment]
I guess I don't really understand what you suggest. I though you asked for storing length as number (only?). If so, round-tripping is a problem, because there are all sorts of ways numbers can be serialized as strings.

**Comment by Anaphory** [comment]
No, I'm asking for `.length` to be arbitrary, so “keep it as a string” would be a valid choice.

I have implemented most of it (with the added benefit of cleaning up some issues where our heavy methods introduce numbers or floating points during cleanup), and I'll show you a pull request in a moment so you can see what you like about it and what not.

**Comment by Anaphory** [comment]
PR in #28 – Have a look at the changes in `test_Node_custom_length()` in particular, to see whether you would find those API changes acceptable.
