### ISSUE TITLE
Redundancy between Node.create and Node.__init__

### ISSUE THREAD

**Issue by Anaphory** [glottobank/python-newick#30]
Why is adding descendants not part of the basic functionality of `Node.__init__`, and is instead exposed by a separate `create` method?

**Comment by xrotwang** [comment]
Since nodes have references to both descendants and their ancestor. So to create a descendant you need an ancestor node. Technically (and also conceptually - at least for me) this is only the case after `__init__` has executed.

**Comment by Anaphory** [comment]
Sounds convincing.
