### ISSUE TITLE
tests module installed into global namespace

### ISSUE THREAD

**Issue by jeromekelleher** [glottobank/python-newick#39]
When the ``newick`` module is installed using pip, the ``tests.py`` module is also installed. This is problematic, because it's unlikely that someone (other than newick developers) calling 

```python
import tests
```
intends to run the ``newick`` test suite.  Looking at the [PyPA tutorial](https://packaging.python.org/tutorials/distributing-packages/#setup-args) I'm not sure that integrating tests into setup.py is encouraged any more. If you do wish to keep it, probably the [test_suite](https://setuptools.readthedocs.io/en/latest/setuptools.html#command-reference) argument is probably what's needed.

In any case, I think ``tests.py`` should be removed from ``py_modules``.

Thanks for ``newick``, it's super useful!

**Comment by xrotwang** [comment]
thanks for the heads-up. I've been in the process of modernizing a couple of other packages lately (moving from nose to pytest, etc.), and will use this opportunity to do the same for this package!
