### ISSUE TITLE
Tree manipulations/moves implementation

### ISSUE THREAD

**Issue by PhyloStar** [glottobank/python-newick#42]
@xrotwang  and @LinguList  It would be nice to have tree moves such as Nearest Neighbor Interchange (NNI) and Subtree Pruning and Regrafting (SPR) implemented in the newick package. These are required for tree search in both parsimony and bayesian algorithms.

NNI example is here: https://media.springernature.com/original/springer-static/image/prt%3A978-1-4939-2864-4%2F14/MediaObjects/978-1-4939-2864-4_14_Part_Fig1-256_HTML.gif

Example of SPR is here: https://slideplayer.com/slide/5308620/17/images/14/Subtree+Pruning+and+Regrafting.jpg

My implementation of NNI is here: https://github.com/pylogeny/bayes/blob/87980f3470d012cf7edac114d98ed056f0241b2b/src/cybayes/commands/mcmc_gamma.pyx#L235

SPR implementation is here:
https://github.com/pylogeny/bayes/blob/87980f3470d012cf7edac114d98ed056f0241b2b/src/cybayes/commands/mcmc_gamma.pyx#L270

I was storing a tree in adjacency list format and then performing tree manipulations around them. @LinguList suggests a new tree manipulator/rearrangement package for our purpose. @xrotwang How should we proceed here?

**Comment by xrotwang** [comment]
I'd opt for new package, possibly reusing the newick Node class.
We wanted to keep the newick package focused and small for better
testability and overall maintenance.

Taraka Rama <notifications@github.com> schrieb am Mo., 22. Juni 2020, 17:48:

**Comment by LinguList** [comment]
We could call it "treeman" for "tree manipulation". We can add it in
https://github.com/pylogeny/ If treeman handles tree manipulation, with
newick as a dependency, it can handle all things that are harder to do,
and we can keep newick as is, in a clean tested version.

**Comment by PhyloStar** [comment]
Okay. Great. Let us keep it that way.

Best,
Taraka

**Comment by LinguList** [comment]
you can start making a repository on pylogeny, I can then set up the
initial setup.py also with a test directory, etc.
