### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jeromekelleher** [glottobank/python-newick#43]
It would be helpful to have a changelog summarising the changes made per release - did I miss it?

**Comment by xrotwang** [comment]
No, sorry, there is none. There also isn't much change in functionality, though. The package is supposed to be pretty basic, so new releases are typically triggered by changes in the environment - such as dropping support for obsolete python versions, or recently supporting read and write operations on `pathlib.Path` objects.

I'll leave the issue open, though, to remind me to start a changelog with the next release.

**Comment by jeromekelleher** [comment]
Great, thanks @xrotwang. I really like that the package is simple, keep up the great work!
