### ISSUE TITLE
include recipe example?

### ISSUE THREAD

**Issue by HedvigS** [glottobank/python-newick#47]
[Would it be possible to include this script as a recipe in this repos?](https://github.com/HedvigS/personal-cldf-cookbook/blob/main/python/create_tree_bottom_up.py) Just as an example of how it could work?

**Comment by xrotwang** [comment]
As far as I can tell, in terms of python-newick functionality, this script does nothing that's not described at https://github.com/dlce-eva/python-newick#manipulating-trees
So - as it is - I think it would be rather confusing, by mixing newick functionality with things like Glottolog family trees, etc.

**Comment by HedvigS** [comment]
That's true, it's equal to the other example with prune_by_names and inverse = T. 

I've encountered people who are trying to do this in other fashions and didn't know that this was possible with pynewick, so I thought a hands-on example with something like glottolog families trees might be useful as it is something many people do. I can point them to the manipulating tree page, but I thought a practical example with data they are most likely using might be a good idea.

**Comment by LinguList** [comment]
@HedvigS, I assume if you post this on your blog, you reach out to more people than to post it here. Typically, the original repository is the last place where people look for recipes in my experience...

**Comment by xrotwang** [comment]
I think this script might be better off as recipe in the Glottolog cookbook, because - from my POV - the most opaque aspect here is the fact that `pyglottolog.languoids.Languoid.newick_node` is a `newick.Node` object. Thus, when you know you should look up python-newick's docs, you are already over the peak of the learning curve.

**Comment by HedvigS** [comment]
> 

Oh okay, I don't have that impression. I often look at example scripts for Python and R-packages at the location where I expect the package to be maintained, I find that to be where I expect such things. But to each their own.

**Comment by HedvigS** [comment]
> I think this script might be better off as recipe in the Glottolog cookbook, because - from my POV - the most opaque aspect here is the fact that `pyglottolog.languoids.Languoid.newick_node` is a `newick.Node` object. Thus, when you know you should look up python-newick's docs, you are already over the peak of the learning curve.

Okay sure, I wouldn't mind it being there instead.
