### ISSUE TITLE
Should newick raise an exception or warning if the tree is invalid?

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/python-newick#49]
Should python-newick raise an exception or warning if the tree is invalid:

```python
>>> a = newick.loads("(A,B,C),D);")[0]
>>> print(a.ascii_art())
    ┌─A
────┤
    └─B
```

This tree needs an extra bracket before "A". Python-newick parses this happily, but the resulting parsed tree is incorrect ('C' and 'D' are silently deleted).

**Comment by xrotwang** [comment]
Yes, I think that should be an error. Things got a little more involved with support for comments and annotations - but AFAICT the basic newick parsing functionality relies on `()` **not** appearing in annotations anyway.

**Comment by xrotwang** [comment]
And while that will break backwards compatibility, I'd still think of this more as a bug fix.
