### ISSUE TITLE
Add a 'translate' ability

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/python-newick#53]
One feature of nexus files is that they allow 'translate' blocks for taxa names, e.g.:

```
#NEXUS
begin trees;
        translate
                1 Cat,
                2 Dog,
                3 Rabbit
                tree = ((1,2)3);
end;
```

Which means that the tree actually parses to `((Cat,Dog)Rabbit)`

This has some benefits -- i.e. you can relabel nodes quickly, and the textual representation is much smaller (which can be a non-trivial saving on diskspace).

There is currently no implementation in python that can handle this (neither `ete3` nor `dendropy` deal with this). Perhaps newick could be extended to enable a taxon translation mapping e.g.:

```python
>>> from newick import loads
>>> trees = loads('((1,2)3);', translate = {'1': 'Cat', '2': 'Dog', '3': 'Rabbit'} )
>>> [n.name for n in trees[0].descendants]
['Cat', 'Dog', 'Rabbit']
```

which would then mean that implementations like `python-nexus` or `commonnexus` could use this to implement `translate` options.

**Comment by xrotwang** [comment]
```python
>>> from newick import loads
>>> trees = loads('((1,2)3);')
>>> trees[0].rename(**{'1': 'Cat', '2': 'Dog', '3': 'Rabbit'}).newick
'((Cat,Dog)Rabbit)'
```

See https://github.com/dlce-eva/python-newick/blob/a8e4049737ac1f5d45b3736e98e872bc5edd004f/src/newick.py#L352-L359

**Comment by xrotwang** [comment]
`commonnexus` can write `TRANSLATE` commands:
```python
>>> from commonnexus import Nexus
>>> from commonnexus.blocks.trees import Trees
>>> print(Nexus.from_blocks(Trees.from_data(('tree', '((1,2)3);', None), **{'1': 'Cat', '2': 'Dog', '3': 'Rabbit'})))
#NEXUS
BEGIN TREES;
	TRANSLATE 1 Cat,
2 Dog,
3 Rabbit;
	TREE tree = ((1,2)3);
END;
```

**Comment by xrotwang** [comment]
`commonnexus` of course also "de-translates":
```python
>>> nex = Nexus.from_blocks(Trees.from_data(('tree', '((1,2)3);', None), **{'1': 'Cat', '2': 'Dog', '3': 'Rabbit'}))
>>> nex.TREES.translate(nex.TREES.TREE).newick
'((Cat,Dog)Rabbit)'
```
