### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by sbooeshaghi** [glottobank/python-newick#54]
Hi! Awesome tool- I've been using it for https://github.com/IGVF/seqspec/ and its been very useful (especially the extensive documentation).

Is there a preprint/paper/citation that I can cite in a corresponding paper?

Thanks!
Sina

**Comment by xrotwang** [comment]
Good to hear you found this package useful! You could possibly cite an earlier version we pushed to Zenodo (https://doi.org/10.5281/zenodo.1215488), but it's really just a small, dedicated tool, so the credits we get by you listing it as a dependency is fine :)
Btw. you [list python 3.6](https://github.com/IGVF/seqspec/blob/c796572ae197ffa7a80784e65017b8c95b5aadc5/setup.py#L37) as compatible version for your library. This won't be compatible with the latest `python-newick` releases, which dropped py3.6 compatibility.
