### ISSUE TITLE
Support NEXUS files?

### ISSUE THREAD

**Issue by lmaurits** [glottobank/python-newick#7]
Its very common to receive trees in NEXUS files which have (1) various comment lines at the top; (2) a "Begin trees;" and "END;" line; (3) "tree FOO = " text before each line containing a tree.  Currently these cannot be loaded directly.  I know we don't want to fall into the trap of trying to support a whole host of obscure formats, but making it painless to use the single most common format is probably a good idea.

**Comment by xrotwang** [comment]
I didn't know that NEXUS files may contain trees in newick format. But rather than adding support for NEXUS reading (and writing?) to our package we may provide an enhanced [`trees` block handler](https://github.com/SimonGreenhill/python-nexus/blob/master/README.md#trees-block-handler) for @SimonGreenhill s [python-nexus](https://github.com/SimonGreenhill/python-nexus) package.

**Comment by lmaurits** [comment]
Ah, I wasn't aware of that package!  Some kind of integration certainly makes sense, but I still think that a very limited native NEXUS support (i..e. ignoring all non-tree blocks and just returning an unlabelled list of Nodes) for this library makes some sense.  Having to import two libraries and (presumably) write some extra lines to tie them together is a small pain if one doesn't want any of the other features of python-nexus.

**Comment by xrotwang** [comment]
Ok, so maybe provide a `from_nexus` parameter for `loads` (and `load` and `read`), which - if `True` - extracts the newick strings from the NEXUS block.

**Comment by QuentinAtkinson** [comment]
This might be an aside, but I have always found the most annoying thing about importing nexus files into various software packages has been when it isn’t clear exactly what format the programme wants or why it is rejecting a file.  It probably goes without saying, but a clear model format and error reporting is really helpful - you’ll never accommodate all the various nexus permutations.  Some of the most common issues are pretty basic though - does the file have a separate taxa block, what data types are valid, does it include trees and how are the trees named, and (for some software) what type of line breaks are used.

Q

On 1 Mar 2016, at 23:18, Robert Forkel <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, so maybe provide a from_nexus parameter for loads (and load and read), which - if True - extracts the newick strings from the NEXUS block.

**Comment by xrotwang** [comment]
Comment by @Anaphory: Often, the tree I want to parse using newick.py comes in a nexus file, with some `taxa` definitions and a `#NEXUS` line and some other garbage (for these intents) before it. That stuff should just be ignored, so that I can just feed such a file to the nexus parser directly.

Even more importantly, sometimes such a file (eg. the one in http://science.sciencemag.org/highwire/filestream/593618/field_highwire_adjunct_files/0/1219669IndoEuropean_2MCCtrees_annotated.zip) contains comments, i.e. text enclosed in `[` and `]`. Ignoring that noise would be helpful.

**Comment by xrotwang** [comment]
We should include the following trees, listed as examples and test suite on the [NESCENT wiki](http://informatics.nescent.org/wiki/Supporting_NEXUS#Test_files_for_NEXUS_parsers), in our test suite:

```
     tree basal_trifurcation = (((A:1,B:1):1,(C:1,D:1):1):1,(E:1,F:1):2,(G:1,H:1):2);
    tree bush = (((A:1,B:1):1,(C:1,D:1):1):1,((E:1,F:1):1,(G:1,H:1):1):1);
    tree bush_branchlength_negative = (((A:1,B:1):1,(C:1,D:1):_0.25):1,((E:1,F:1):1,(G:1,H:1):1):1);
    tree bush_branchlength_scientific = (((A:1,B:2e+01):1,(C:9e_01,D:1):1):1,((E:1,F:9E_01):1,(G:2E+01,H:1):1):1);
    tree bush_branchlength_zero = (((A:1,B:1):1,(C:0,D:1):1):1,((E:1,F:1):1,(G:1,H:1):1):1);
    tree bush_cladogram = (((A,B),(C,D)),((E,F),(G,H)));
    tree bush_extended_root_branch = (((A:1,B:1):1,(C:1,D:1):1):1,((E:1,F:1):1,(G:1,H:1):1):1):1;
    tree bush_inode_labels = (((A:1,B:1)AB:1,(C:1,D:1)CD:1)ABCD:1,((E:1,F:1)EF:1,(G:1,H:1)GH:1)EFGH:1);
    tree bush_inode_labels_partial = (((A:1,B:1):1,(C:1,D:1):1):1,((E:1,F:1)EF:1,(G:1,H:1)GH:1)EFGH:1);
    tree bush_inode_labels_quoted2 = (((A:1,B:1)'inode AB':1,(C:1,D:1)'inode CD':1)'inode ABCD':1,((E:1,F:1)'inode EF':1,(G:1,H:1)'inode GH':1)'inode EFGH':1);
    tree 'bush quoted string name2' = (((A:1,B:1):1,(C:1,D:1):1):1,((E:1,F:1):1,(G:1,H:1):1):1);
    tree bush_uneven = (((A:1,B:2):1,(C:1,D:2):1):1,((E:1,F:2):1,(G:1,H:2):1):1);
    tree ladder = (((((((A:1,B:1):1,C:2):1,D:3):1,E:4):1,F:5):1,G:6):1,H:7);
    tree ladder_cladogram = (((((((A,B),C),D),E),F),G),H);
    tree ladder_uneven = (((((((A:1,B:2):1,C:2):1,D:4):1,E:4):1,F:6):1,G:6):1,H:8);
    tree rake = (A:1,B:1,C:1,D:1,E:1,F:1,G:1,H:1);
    tree rake_cladogram = (A,B,C,D,E,F,G,H);
```
