### ISSUE TITLE
newick.py should ignore Nexus chattiness and comments

### ISSUE THREAD

**Issue by Anaphory** [glottobank/python-newick#8]
Often, the tree I want to parse using newick.py comes in a nexus file, with some `taxa` definitions and a `#NEXUS` line and some other garbage (for these intents) before it. That stuff should just be ignored, so that I can just feed such a file to the nexus parser directly.

Even more importantly, sometimes such a file (eg. the one in http://science.sciencemag.org/highwire/filestream/593618/field_highwire_adjunct_files/0/1219669IndoEuropean_2MCCtrees_annotated.zip) contains comments, i.e. text enclosed in `[` and `]`. Ignoring that noise would be helpful.

**Comment by xrotwang** [comment]
Moved to a comment on #7 : https://github.com/glottobank/python-newick/issues/7#issuecomment-191170359
